[blockchain_access]
rusk_address = "http://127.0.0.1:8080"
#rusk_address = "https://devnet.nodes.dusk.network/"
#rusk_address = "https://testnet.nodes.dusk.network/"
prover_address = "http://127.0.0.1:8080"
#prover_address = "https://devnet.provers.dusk.network/"
#prover_address = "https://testnet.provers.dusk.network/"
